spring.application.name=certificate-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/placement_db
spring.datasource.username=postgres
spring.datasource.password=Max2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
